nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE', 'PATCH']
            expose_headers: ['Link']
            max_age: 3600
            hosts: []
            origin_regex: true
            forced_allow_origin_value: ~
        paths:
            '^/':
                allow_origin: ['*']
                allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600

                
