#header('Access-Control-Allow-Origin: *');
#header("Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method");
#header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
#header("Allow: GET, POST, OPTIONS, PUT, DELETE");
#$method = $_SERVER['REQUEST_METHOD'];
#if($method == "OPTIONS") {
#    die();
#}

nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE', 'PATCH']
            expose_headers: ['Link']
            max_age: 3600
            hosts: []
            origin_regex: true
            forced_allow_origin_value: ~